/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function encodeDefaultFromJsonString(jsonString: string): string
export function decodeToJsonString(encodedString: string): string
